name: Build and Release

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main]
  workflow_dispatch: {} # Allow manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-with-cuda:
    runs-on: ubuntu-latest
    container:
      image: pytorch/pytorch:2.6.0-cuda12.6-cudnn9-devel
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
            cmake ninja-build git
          pip install --no-cache-dir build wheel setuptools

      - name: Verify CUDA installation
        run: |
          nvcc -V
          python -c "import torch; print(f'PyTorch version: {torch.__version__}'); print(f'CUDA available: {torch.cuda.is_available()}')"
          echo "CUDA_PATH=${CUDA_HOME}"

      - name: Build wheel
        run: bash .github/scripts/real-build.sh
        env:
          CUDA_PATH: ${CUDA_HOME}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/*.whl
          retention-days: 7

  publish-release:
    needs: build-with-cuda
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only run on main branch
    permissions:
      contents: write
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          name: wheel
          path: wheels/

      - name: List wheels
        run: ls -la wheels/

      - name: Create/Update Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: wheels/*.whl
          prerelease: true
          name: Latest Build from main
          tag_name: continuous-release
          make_latest: true
          draft: false
          target_commitish: ${{ github.sha }}