name: Build and Release

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main]
  workflow_dispatch: {} # Allow manual trigger

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.8.0-devel-ubuntu22.04
      options: --gpus all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python and dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            python3 \
            python3-pip \
            python3-dev \
            python3-setuptools \
            python3-wheel \
            git \
            build-essential \
            cmake

      - name: Run build script
        run: |
          chmod +x .github/scripts/real-build.sh
          .github/scripts/real-build.sh

      - name: Upload wheel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/*.whl
          retention-days: 7

  create-release:
    needs: build-wheel
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Download wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: wheel
          path: wheels/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: wheels/*.whl
          prerelease: true
          name: Latest build from main
          tag_name: continuous-build
          make_latest: true
          draft: false
          target_commitish: ${{ github.sha }} 